[[IVerilog]]
arch = "aarch64"
git-tree-sha1 = "b27dbf91d0e2fe339706a7feb9a19bc9fdbbedcb"
os = "macos"

    [[IVerilog.download]]
    sha256 = "5d4176438d33217d7ad38ccac17cf1876cc6c87e65c615063d40b481a8a46dcf"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.aarch64-apple-darwin.tar.gz"
[[IVerilog]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "989ced3614ff9f88f3388d433fe13890c78250ef"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "fea6b379b5ff72fd1ebcd05f02972765bdc06971358842fd66ab57f0919441f1"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[IVerilog]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "faeca34f95f151da75fdd15d93a2633c051d61ad"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "f49243c4b16ec55af84f1706ca3559ffeec98417dea62524a3c61f0c7a99e780"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[IVerilog]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26ca22186a66803c424196716d9df5443d3d10cd"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "5a1b42a551cb7b2840e4653c3b8eb5f50c5a746de37378f2666f96df2c522db7"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[IVerilog]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0aabc4de4fca3a89a271edc528818a91fbcf239a"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "3d513fce58f96af3f7580fc55cc9edcc47f47b3bb0c0e3fe755b23960758b088"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[IVerilog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d806cc6b2c040b065b76fbd7e57edcf65d12a67c"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "96e692f0d9d1b28c5453c271747feb9362e617b622e557f931ac26c08ee2f979"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[IVerilog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b80df3f89ba5e8024f498cf262ebe6fd251740a"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "18509b54f0a09c750b38b08abd7c94630ce965e363254f05015fb32547073f4b"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[IVerilog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67d2cf86ca1811fc8ec6f5bf5702f8c50fe3c263"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "ea181a8c222faeb097a032e949dc9bb607ac41c5614021317d377fda73305250"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[IVerilog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a505e04286f5dea28eb399d0fef4fb85bfcfa741"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "ab91b95e587b8ac32b0ab45823230e355bf173d516109c911cd17e002607fa5e"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[IVerilog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f94088141e92a5b9d7e69c027be3a318b55c64d"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "d1f48ca4fc6e348056feb3a68f6399bb25c54cf8bc960e6b6679c0d45dcca22b"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[IVerilog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb68306d31bdfa60b7c94bed0a7395c1ffd730bf"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "1bc472473cb52203015e8ea145289268a2b6b9e636098b80b00341dd0dbaee38"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[IVerilog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89ffa9baab372616115aef136a12c6feb69c9d12"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "a970bd15f64c0b3f1599c85415d3c0223baeea0a7b104b0a185b0d34aa6387d7"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[IVerilog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e9223d98b1094b9411fcb7e949b1a4732cdaa6d"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "774a883589fe1e58d40031273f255f877598c2c6259a7bba39ae8f4034dfbf7a"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[IVerilog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f5d3e08e03277aeee44a867c75c0c8905f48523"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "8fd1fead5f983dcaccefecf3365dd799729e3622688435a1350eb5250162d571"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[IVerilog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3f178ca3bc6b43b3e944f188b0eaebeebdddf38"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "8d941bfe12c9a90aa9e9f28c1cebd9e3ffac6bd6a42367a461ea99934fbfcbb5"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[IVerilog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac38d649f581d92b3aa2695b6268d59a2e5704db"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "98315d18f92ac019a82c246b2084bba340b328bbda310372ba9358e7d0cf9ef8"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[IVerilog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0384df2953d4c77eeef3c6fda16f218e378741c"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "d1f85741147cde135f022eb88c579651ba781e8fbae20b3c68fcca2c30ebe9ca"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[IVerilog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa33031698dd4a96bb8f61e3e64901ed8b5a2054"
os = "windows"

    [[IVerilog.download]]
    sha256 = "79543a2264a0f2301574e9f525e9ec9643951489c50c568a96957aa7a1c1e313"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[IVerilog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83f79dc9dddf822ac290aedf0b0c519b4401b61b"
os = "windows"

    [[IVerilog.download]]
    sha256 = "83925372b2e8890b7e6e5f2f5d1ea54c8fde63c481f8ed46e12123ad350b8670"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[IVerilog]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7af3d5c666452bdcc068db6c48207238f8af5eb"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "da3fc2184d3e9085971ebce88a713632814183d8ea5532bad253a9b4ce616698"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[IVerilog]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c666c146c4c326914b5d48a75b0bb90294f4039"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "a44d40f37ab94914c5241e17e6931346e17a4924f24ec30ec2b103fa86278a9f"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[IVerilog]]
arch = "x86_64"
git-tree-sha1 = "1b8af2ec38dace8c9098c9cf31a7bb135c2e1ef8"
os = "macos"

    [[IVerilog.download]]
    sha256 = "585e920f5f4fedce7e75d3bf96b4ed33a93e1e309e78b641836ab49b5ccf28e0"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-apple-darwin.tar.gz"
[[IVerilog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f6cc4adfc235e9ba6add828aecdda418050c854"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "f98b1c613b8be5435b996ddcb46870303943e48367030f13fa57e80290bfd677"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[IVerilog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00054b88a098eae2b6c1f0eea67f0b5da3942e76"
libc = "glibc"
os = "linux"

    [[IVerilog.download]]
    sha256 = "21927414d86abb9145931524facef92ef9feb54011b4618a1bd9fa20d5341cfc"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[IVerilog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e59f030373a8265497f930f5f121df40e3686283"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "5d8e0cd2e68d0f2edc603d157e5e5582e44d009762a0e02d87d7c413fd696796"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[IVerilog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "058ec3f47d6d155880a7764252cf960d7e5b7bf9"
libc = "musl"
os = "linux"

    [[IVerilog.download]]
    sha256 = "a80aae21b63dc8522fd0ccfbef8c221079fa2cf23668968520ea56ca4294bebf"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[IVerilog]]
arch = "x86_64"
git-tree-sha1 = "b4d33ad45c2d9a4549a70de3c667df1a386e78b4"
os = "freebsd"

    [[IVerilog.download]]
    sha256 = "759029eb5a3ee64a16f0b6eec2a948f953c246590085633cca02d0594b31f51c"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[IVerilog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3bcbbd6b2f5ecdbbdaa66adb3d15753d3021097"
os = "windows"

    [[IVerilog.download]]
    sha256 = "ab3b0680168a8d986a93fd65b1c926af125f5dcd907d3595385008bd0a823106"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[IVerilog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f679838f12422ac276d3ffcfd20292908311b6b"
os = "windows"

    [[IVerilog.download]]
    sha256 = "26a51f09a29a693caab7c4cfdcc0efd4f9066a01a8a010ad5cf1a2f17f87f637"
    url = "https://github.com/JuliaBinaryWrappers/IVerilog_jll.jl/releases/download/IVerilog-v12.0.0+1/IVerilog.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
